#this is a makefile for java program on client and server

FLAG1 = -cp
JARFilES = .:ajt.jar:jama.jar:javaml.jar

ClientMain.class: ClientMain.java
	javac ClientMain.java
Client.class: Client.java
	javac Client.java
ServerMain.class: ServerMain.java
	javac ServerMain.java
Server.class: Server.java
	javac Server.java
SendFile2Server.class: SendFile2Server.java
	javac ./ML/SendFile2Server.java
ReceiveFileFromClient.class: ReceiveFileFromClient.java
	javac ./ML/ReceiveFileFromClient.java